apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: demo
    tier: frontend
    track: stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: "achalise/demo-frontend"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 8888
      targetPort: 80
  selector:
    app: demo
    tier: frontend
  type: NodePort

